### PR TITLE
Test and fix build check

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by sebastienros** [comment]
@rivantsov it's working, and showing that one test is failing. I will use this PR to fix the test.

The appveyor integration can only be removed from appveyor itself.

**Comment by rivantsov** [comment]
appveyor - I did not add it. I followed links, tried to login there thru github account, but it gave me 'blank' account, no existing integrations. don't remember who added this. Is there a way now to disable it? and by the way, I don't mind disabling the build itself

**Comment by sebastienros** [comment]
@yallie you seem to own the appveyor project that is linked to this repository? Can you please delete it now that we have integrated GitHub actions?

**Comment by yallie** [comment]
Hi! 
I deleted the linked Appveyor project, should be no Appveyor checks on PRs anymore.
Thanks @sebastienros for pointing it out!

**Pull request merged**
