### PR TITLE
Target .NET Standard 1.6 instead of .NET Standard 2.0

### PR DESCRIPTION
**Pull request by igitur**
This PR is still work in progress

Change to netstandard1.6 so that other project, e.g. XLParser can use this fork of Irony as dependency.

### CODE REVIEW

**Comment by igitur** [comment]
Please don't merge yet.

**Comment by yallie** [comment]
>Please don't merge yet.

Hi, is this still work in progress?

**Comment by igitur** [comment]
Yes, sorry, juggling so many balls at the moment.

**Comment by yallie** [comment]
No problem!
Just thought that maybe it's already OK as the Appveyor build succeeds.

**Pull request closed without merging**
